# Generated by Django 2.1.5 on 2019-06-04 16:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=50)),
                ('anger_count', models.IntegerField(default=0)),
                ('tense_count', models.IntegerField(default=0)),
                ('micro_anger_count', models.IntegerField(default=0)),
                ('micro_tense_count', models.IntegerField(default=0)),
                ('anger_timestamp', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tense_timestamp', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('micro_anger_timestamp', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('micro_tense_timestamp', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('finish_processing', models.BooleanField()),
            ],
        ),
    ]
