# Generated by Django 2.1.5 on 2019-06-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhetoric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='error',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
